









#define FC_FUNC(name,NAME) name ## _


#define FC_FUNC_(name,NAME) name ## _


#define HAVE_ALIGNED_ALLOC 1


#define HAVE_CLOCK_GETTIME 1


#define HAVE_FC_FLUSH 1





#define HAVE_FC_GET_COMMAND_ARGUMENT 1





#define HAVE_INTTYPES_H 1


#define HAVE_LIBDL 1


#define HAVE_LIBRT 1


#define HAVE_MEMORY_H 1


#define HAVE_MPI2 1


#define HAVE_MPI_INIT_THREAD 1














#define HAVE_STDINT_H 1


#define HAVE_STDLIB_H 1


#define HAVE_STRINGS_H 1


#define HAVE_STRING_H 1


#define HAVE_STRNDUP 1


#define HAVE_SYS_STAT_H 1


#define HAVE_SYS_TYPES_H 1


#define HAVE_TIME_H 1


#define HAVE_UNISTD_H 1


#define PACKAGE "futile"


#define PACKAGE_BUGREPORT "Damien.Caliste@cea.fr"


#define PACKAGE_NAME "Futile"


#define PACKAGE_STRING "Futile 1.8"


#define PACKAGE_TARNAME "futile"


#define PACKAGE_URL ""


#define PACKAGE_VERSION "1.8"


#define STDC_HEADERS 1


#define VERSION "1.8"
